---
- hosts: all
  become: yes
  roles:
    - role: ansible-opendaylight
      # ODL is already installed, so no need to specify installation method.  Specify extra features to install
      extra_features:
          - odl-restconf-all 
          - odl-mdsal-all
          - odl-mdsal-apidocs
          - odl-daexim-all
          - ccsdk-sli-core-all
          - ccsdk-sli-adaptors-all
          - ccsdk-sli-northbound-all
          - ccsdk-sli-plugins-all