version: '2'

services:
  db:
    image: mysql/mysql-server:5.6
    container_name: ccsdk_db_container
    ports:
      - "3306"
    environment:
      - MYSQL_ROOT_PASSWORD=openECOMP1.0
      - MYSQL_ROOT_HOST=%
    logging:       
      driver:   "json-file"
      options:  
        max-size: "30m"
        max-file: "5"
  
      
  odlsli:
    image: ${NEXUS_DOCKER_REPO}/onap/ccsdk-odlsli-alpine-image:${CCSDK_DOCKER_IMAGE_VERSION}
    depends_on :
      - db
    container_name: ccsdk_odlsli_container
    entrypoint: ["/opt/onap/ccsdk/bin/startODL.sh"]
    ports:
      - "8383:8181"
    links:
      - db:dbhost
      - db:sdnctldb01
      - db:sdnctldb02
    environment:
      - MYSQL_ROOT_PASSWORD=openECOMP1.0
      - SDNC_CONFIG_DIR=/opt/onap/ccsdk/data/properties
    logging:       
      driver:   "json-file"
      options:  
        max-size: "30m"
        max-file: "5"
  
  dgbuilder:
    image: ${NEXUS_DOCKER_REPO}/onap/ccsdk-dgbuilder-image:${CCSDK_DOCKER_IMAGE_VERSION}
    depends_on:
      - db
    container_name:  ccsdk_dgbuilder_container
    entrypoint:
       - "/bin/bash"
       - "-c"
       - "cd /opt/onap/ccsdk/dgbuilder/ && ./start.sh sdnc1.0 && wait"
    ports:
      - "3000:3100"
    links:
      - db:dbhost
      - db:sdnctldb01
      - db:sdnctldb02
      - odlsli:sdnhost
    environment:
      - MYSQL_ROOT_PASSWORD=openECOMP1.0
      - SDNC_CONFIG_DIR=/opt/onap/ccsdk/data/properties
    logging:       
      driver:   "json-file"
      options:  
        max-size: "30m"
        max-file: "5"
  
  
