module.exports = {
		'name' : 'Release 1702',
		'emailAddress' :'change_email_id@dgbuilder.com',
		'uiPort' :3100,
		'mqttReconnectTime': 15000,
		'serialReconnectTime' : 15000,
		'debugMaxLength': 1000,
		'htmlPath': 'releases/1702/html/',
		'xmlPath': 'releases/1702/xml/',
		'flowFile' : 'releases/1702/flows/flows.json',
		'sharedDir': 'releases/1702/flows/shared',
		'userDir' : 'releases/1702',
		'httpAuth': {user:'dguser',pass:'cc03e747a6afbbcbf8be7668acfebee5'},
		'dbHost': 'dbhost',
		'dbPort': '3306',
		'dbName': 'sdnctl',
		'dbUser': 'sdnctl',
		'dbPassword': 'gamma',
		'gitLocalRepository': ''
		}
