version: '2.1'

services:
  db:
    image: mariadb:10.5
    container_name: odlsli_db
    ports:
      - "3306"
    environment:
      - MYSQL_ROOT_PASSWORD=MySecretPassword
      - MYSQL_ROOT_HOST=%
    logging:       
      driver:   "json-file"
      options:  
        max-size: "30m"
        max-file: "5"
  
      
  odlsli:
    image: onap/ccsdk-odlsli-alpine-image:latest
    depends_on:
      - db
    container_name: odlsli_controller
    entrypoint: ["/opt/onap/ccsdk/bin/startODL.sh"]
    ports:
      - "8383:8181"
      - "1830:1830"
      - "8543:8443"
    links:
      - db:dbhost
      - db:sdnctldb01
      - db:sdnctldb02
    environment:
      - MYSQL_ROOT_PASSWORD=MySecretPassword
      - SDNC_CONFIG_DIR=/opt/onap/ccsdk/data/properties
      - JAVA_OPTS=-Xms512m -Xmx2048m
    logging:       
      driver:   "json-file"
      options:  
        max-size: "30m"
        max-file: "5"

  dgbuilder:
    image: onap/ccsdk-dgbuilder-image:latest
    depends_on:
      - db
    container_name:  odlsli_dgbuilder
    entrypoint:
       - "/bin/bash"
       - "-c"
       - "cd /opt/onap/ccsdk/dgbuilder/ && ./start.sh sdnc1.0 && wait"
    ports:
      - "3200:3100"
    links:
      - db:dbhost
      - db:sdnctldb01
      - db:sdnctldb02
    environment:
      - MYSQL_ROOT_PASSWORD=MySecretPassword
      - SDNC_CONFIG_DIR=/opt/onap/ccsdk/data/properties
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
    logging:
      driver:   "json-file"
      options:
        max-size: "30m"
        max-file: "5"

